/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.YoiHenken;

import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author yoihenken
 */
public class JMain extends javax.swing.JFrame {

    /**
     * Creates new form JMain
     */
    public JMain() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        bilDis2 = new javax.swing.JTextField();
        bilAllow = new javax.swing.JTextField();
        bilDis1 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        bilRangeEnd = new javax.swing.JTextField();
        buttonReset = new javax.swing.JButton();
        buttonConfirm1 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        bilRangeStart = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        lbl_Allow = new javax.swing.JLabel();
        lbl_rangeEnd = new javax.swing.JLabel();
        areaOutput = new java.awt.TextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel4.setText("Diperbolehkan");

        jLabel1.setText("Kelipatan");

        jLabel2.setText("Tidak diperbolehkan");

        jLabel3.setText("Kelipatan");

        jLabel5.setText("Kelipatan");

        jLabel6.setText("PROGRAM MENAMPILKAN KELIPATAN BILANGAN");

        bilDis2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bilDis2ActionPerformed(evt);
            }
        });

        bilAllow.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bilAllowActionPerformed(evt);
            }
        });

        bilDis1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bilDis1ActionPerformed(evt);
            }
        });

        jLabel7.setText("Jarak");

        bilRangeEnd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bilRangeEndActionPerformed(evt);
            }
        });

        buttonReset.setText("Reset");
        buttonReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonResetActionPerformed(evt);
            }
        });

        buttonConfirm1.setText("Confirm");
        buttonConfirm1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonConfirm1ActionPerformed(evt);
            }
        });

        jLabel8.setText("DENGAN SYARAT TERTENTU");

        bilRangeStart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bilRangeStartActionPerformed(evt);
            }
        });

        jLabel9.setText("Mulai");

        jLabel10.setText("Akhir");

        jLabel11.setText("--------------------");

        jLabel12.setText("----------------------------");

        jLabel13.setText("----------------");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(104, 104, 104)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel11))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel13))
                            .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGap(36, 36, 36)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel5)
                                            .addComponent(jLabel3))
                                        .addGap(31, 31, 31)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(bilDis1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(bilDis2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel1)
                                        .addGap(31, 31, 31)
                                        .addComponent(bilAllow, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jLabel10)
                                    .addComponent(jLabel9))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lbl_Allow, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel12)))
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(buttonConfirm1)
                                .addGap(59, 59, 59)
                                .addComponent(buttonReset)
                                .addGap(183, 183, 183))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(areaOutput, javax.swing.GroupLayout.PREFERRED_SIZE, 286, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(147, 147, 147))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(bilRangeStart, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(bilRangeEnd, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(lbl_rangeEnd, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(34, 34, 34))))))
            .addGroup(layout.createSequentialGroup()
                .addGap(173, 173, 173)
                .addComponent(jLabel8)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel8)
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1)
                        .addComponent(bilAllow, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lbl_Allow, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel13))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(bilDis1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(bilDis2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jLabel12))
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bilRangeStart, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel10)
                        .addComponent(bilRangeEnd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lbl_rangeEnd, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonConfirm1)
                    .addComponent(buttonReset))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(areaOutput, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bilDis2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bilDis2ActionPerformed
        // TODO add your handling code here:
        bilDis2.setText(null);
    }//GEN-LAST:event_bilDis2ActionPerformed

    private void bilAllowActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bilAllowActionPerformed
        // TODO add your handling code here:
        bilAllow.setText(null);
    }//GEN-LAST:event_bilAllowActionPerformed

    private void bilDis1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bilDis1ActionPerformed
        // TODO add your handling code here:
        bilDis1.setText(null);
    }//GEN-LAST:event_bilDis1ActionPerformed

    private void bilRangeEndActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bilRangeEndActionPerformed
        // TODO add your handling code here:
        bilRangeEnd.setText(null);
    }//GEN-LAST:event_bilRangeEndActionPerformed

    private void buttonResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonResetActionPerformed
        // TODO add your handling code here:
        bilAllow.setText(null);
        bilDis1.setText(null);
        bilDis2.setText(null);
        bilRangeStart.setText(null);
        bilRangeEnd.setText(null);
        lbl_rangeEnd.setText(null);
        lbl_Allow.setText(null);
    }//GEN-LAST:event_buttonResetActionPerformed

    private void buttonConfirm1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonConfirm1ActionPerformed
        // TODO add your handling code here:
        //Jika "jarak awal", "kelipatan yang tidak diperbolehkan" tidak diisi
        if (bilDis1.getText().trim().isEmpty()) {
            bilDis1.setText("0");
        }
        if (bilDis2.getText().trim().isEmpty()) {
            bilDis2.setText("0");
        }
        if (bilRangeStart.getText().trim().isEmpty()) {
            bilRangeStart.setText("0");
        }
        //Jika "jarak akhir" dan "kelipatan yang diperbolehkan" tidak diisi
        if (bilRangeEnd.getText().trim().isEmpty() && bilAllow.getText().trim().isEmpty()) {
            lbl_rangeEnd.setText("Jangan Kosong");
            lbl_Allow.setText("Jangan Kosong");
        } else if (bilAllow.getText().trim().isEmpty()) {
            lbl_Allow.setText("Jangan Kosong");
        } else if (bilRangeEnd.getText().trim().isEmpty()) {
            lbl_rangeEnd.setText("Jangan Kosong");
        } else {
            lbl_rangeEnd.setText(null);
            lbl_Allow.setText(null); 
            //Jika syarat terpenuhi maka jalankan program
            //Deklarasi
            ArrayList<Integer> arara = new ArrayList<>();
            int mulAllow = Integer.parseInt(bilAllow.getText());
            int mulDis1 = Integer.parseInt(bilDis1.getText());
            int mulDis2 = Integer.parseInt(bilDis2.getText());
            int rangeStart = Integer.parseInt(bilRangeStart.getText());
            int rangeEnd = Integer.parseInt(bilRangeEnd.getText());
            int y;

            //cek kasus
            boolean dis1 = true;
            boolean dis2 = true;

            if (mulDis1 == 0) {
                dis1 = false;
            }
            if (mulDis2 == 0) {
                dis2 = false;
            }
            //Jika tidak ada pengecualian
            if (dis1 == false && dis2 == false) {
                for (int i = 1; i < rangeEnd; i++) {
                    y = except_none_kelipatan(i, mulAllow, rangeStart, rangeEnd);
                    if (y != -1) {
                        arara.add(y);
                    }
                }
            } //Jika pengecualian pada kelipatan pertama
            else if (dis1 == true && dis2 == false) {
                for (int i = 0; i < rangeEnd; i++) {
                    y = except_one_kelipatan(i, mulAllow, mulDis1, rangeStart, rangeEnd);
                    if (y != -1) {
                        arara.add(y);
                    }
                }
            } //Jika pengecualian pada kelipatan kedua
            else if (dis1 == false && dis2 == true) {
                for (int i = 0; i < rangeEnd; i++) {
                    y = except_two_kelipatan(i, mulAllow, mulDis2, rangeStart, rangeEnd);
                    if (y != -1) {
                        arara.add(y);
                    }
                }
            } //Jka pengecualian ada dua
            else if (dis1 == true && dis2 == true) {
                for (int i = 0; i < rangeEnd; i++) {
                    y = except_all_kelipatan(i, mulAllow, mulDis1, mulDis2, rangeStart, rangeEnd);
                    if (y != -1) {
                        arara.add(y);
                    }
                }
            }

            //Memanggil method output
            areaOutput.setText(output(arara));
        }
    }//GEN-LAST:event_buttonConfirm1ActionPerformed

    //Method jika tanpa pengecualian
    public static int except_none_kelipatan(int x, int mulAllow, int rangeStart, int rangeEnd) {
        //Deklarasi
        boolean cek = cek_range(x, rangeStart, rangeEnd);
        if (x % mulAllow == 0 && cek) {
            return x;
        }
        return -1;
    }

    //Method jika pengecualian pertama
    public static int except_one_kelipatan(int x, int mulAllow, int mulDis1, int rangeStart, int rangeEnd) {
        //Deklarasi
        boolean cek = cek_range(x, rangeStart, rangeEnd);
        if (x % mulAllow == 0 && cek) {
            if (x % mulDis1 != 0) {
                return x;
            }
        }
        return -1;
    }

    //Method jika pengecualian kedua
    public static int except_two_kelipatan(int x, int mulAllow, int mulDis2, int rangeStart, int rangeEnd) {
        //Deklarasi
        boolean cek = cek_range(x, rangeStart, rangeEnd);
        if (x % mulAllow == 0 && cek) {
            if (x % mulDis2 != 0) {
                return x;
            }
        }
        return -1;
    }

    //Method jika pengecualian semuanya
    public static int except_all_kelipatan(int x, int mulAllow, int mulDis1, int mulDis2, int rangeStart, int rangeEnd) {
        //Deklarasi
        boolean cek = cek_range(x, rangeStart, rangeEnd);
        if (x % mulAllow == 0 && cek) {
            if (x % mulDis1 != 0 && x % mulDis2 != 0) {
                return x;
            }
        }
        return -1;
    }

    //Method cek range
    public static boolean cek_range(int x, int rangeStart, int rangeEnd) {
        if (x >= rangeStart && x <= rangeEnd) {
            return true;
        }
        return false;
    }

    //Method untuk output
    public static String output(ArrayList<Integer> arara) {
        String out = "";
        for (int i = 0; i < arara.size(); i++) {
            out += String.valueOf(arara.get(i));
            if ((i + 1) < arara.size()) {
                out += ", \n";
            } else {
                out += ".\n";
            }
        }
        return out;
    }

    private void bilRangeStartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bilRangeStartActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bilRangeStartActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JMain().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.TextArea areaOutput;
    private javax.swing.JTextField bilAllow;
    private javax.swing.JTextField bilDis1;
    private javax.swing.JTextField bilDis2;
    private javax.swing.JTextField bilRangeEnd;
    private javax.swing.JTextField bilRangeStart;
    private javax.swing.JButton buttonConfirm1;
    private javax.swing.JButton buttonReset;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel lbl_Allow;
    private javax.swing.JLabel lbl_rangeEnd;
    // End of variables declaration//GEN-END:variables
}
